spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true

cloudinary:
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
  cloud_name: ${CLOUDINARY_NAME}

jwt:
  signer-key: ${SIGNER_KEY}
  expiry-duration: ${EXPIRY_DURATION}
